//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenCompra
    {
        public int Id { get; set; }
        public int NumeroOrden { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Estado { get; set; }
        public int Cantidad { get; set; }
        public double CostoUnitario { get; set; }
        public int SolicitudArticulosId { get; set; }
    
        public virtual SolicitudArticulos SolicitudArticulo { get; set; }
    }
}
