//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        public Proveedores()
        {
            this.Marcas = new HashSet<Marcas>();
        }
    
        public int Id { get; set; }
        public string Cedula { get; set; }
        public string NombreComercial { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<Marcas> Marcas { get; set; }
    }
}
