//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudArticulos
    {
        public SolicitudArticulos()
        {
            this.OrdenCompras = new HashSet<OrdenCompra>();
        }
    
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Estado { get; set; }
        public int Cantidad { get; set; }
        public int ArticulosId { get; set; }
        public int EmpleadosId { get; set; }
    
        public virtual Articulos Articulo { get; set; }
        public virtual Empleados Empleado { get; set; }
        public virtual ICollection<OrdenCompra> OrdenCompras { get; set; }
    }
}
