//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionex.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Marcas
    {
        public Marcas()
        {
            this.Articulos = new HashSet<Articulos>();
        }

        [DisplayName("Marca")]
        public int Id { get; set; }
        [DisplayName("Marca")]
        [Required]
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int ProveedoresId { get; set; }
        [DefaultValue(true)]
        public bool Estado { get; set; }
    
        public virtual Proveedores Proveedor { get; set; }
        public virtual ICollection<Articulos> Articulos { get; set; }
    }
}
