//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionex.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Proveedores
    {
        public Proveedores()
        {
            this.Marcas = new HashSet<Marcas>();
        }

        [DisplayName("Proveedor")]
        public int Id { get; set; }
        [DisplayName("Nombre comercial")]
        [Required]
        public string NombreComercial { get; set; }
        [DisplayName("Cedula / RNC")]
        [Required]
        [RegularExpression(@"^[\d-]*$", ErrorMessage = "Solo debe contener números y guiones ('-')")]
        public string Cedula { get; set; }
        [DefaultValue(true)]
        public bool Estado { get; set; }
    
        public virtual ICollection<Marcas> Marcas { get; set; }
    }
}
