//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionex.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Empleados
    {
        public Empleados()
        {
            this.SolicitudArticulos = new HashSet<SolicitudArticulos>();
        }

        [DisplayName("Empleado")]
        public int Id { get; set; }
        [Required]
        public string Nombre { get; set; }
        [Required]
        public string Apellido { get; set; }
        [Required]
        [RegularExpression(@"^[\d-]*$", ErrorMessage = "Solo debe contener números y guiones ('-')")]
        public string Cedula { get; set; }
        [Required]
        public int DepartamentosId { get; set; }
        [DefaultValue(true)]
        public bool Estado { get; set; }
    
        public virtual Departamentos Departamento { get; set; }
        public virtual ICollection<SolicitudArticulos> SolicitudArticulos { get; set; }
    }
}
