//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionex.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class OrdenCompra
    {
        [DisplayName("No. de Orden")]
        public int Id { get; set; }
        [DisplayName("No. de Orden")]
        [Required]
        public int NumeroOrden { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Fecha { get; set; }
        [Required]
        public int Cantidad { get; set; }
        [DisplayName("Costo por unidad")]
        [Required]
        [DataType(DataType.Currency)]
        public double CostoUnitario { get; set; }
        public int SolicitudArticulosId { get; set; }
        [DefaultValue(true)]
        public bool Estado { get; set; }
        [DataType(DataType.Currency)]
        public double CostoTotal { get => CostoUnitario * Cantidad; }

        public virtual SolicitudArticulos SolicitudArticulo { get; set; }
    }
}
