//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionex.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SolicitudArticulos
    {
        public SolicitudArticulos()
        {
            this.OrdenCompras = new HashSet<OrdenCompra>();
        }

        [DisplayName("Solicitud de artículo")]
        public int Id { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Fecha { get; set; }
        [Required]
        [Range(0, 10000000)]
        public int Cantidad { get; set; }
        [Required]
        public int ArticulosId { get; set; }
        [Required]
        public int EmpleadosId { get; set; }
        [DefaultValue(true)]
        public bool Estado { get; set; }

        public string Resumen { get => $"[{Fecha:yyyy-MM-dd}] {Articulo.Nombre} ({Cantidad} {Articulo.UnidadMedida.Nombre}) - Empleado {Empleado.Nombre} {Empleado.Apellido}"; }
    
        public virtual Articulos Articulo { get; set; }
        public virtual Empleados Empleado { get; set; }
        public virtual ICollection<OrdenCompra> OrdenCompras { get; set; }
    }
}
